export const newsArray = [
	{
		title:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab sit culpa labore officia nam ipsum accusamus quod. Delectus mollitia ipsum explicabo praesentium maxime consequatur corporis non magni eaque debitis repudiandae, necessitatibus nihil quae animi laudantium expedita ab itaque eius placeat voluptatem ducimus voluptas excepturi inventore. Nobis adipisci sequi odit maxime cum est ipsam. Suscipit minima vitae nulla tenetur dolor quam ratione fugit. Modi rerum officia cumque ratione facilis possimus asperiores quaerat adipisci explicabo qui sed architecto, exercitationem saepe autem ipsam!',

		detail:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, quis. Pariatur, atque harum culpa provident tempore earum! Cupiditate earum quaerat nihil perferendis? Quas illum, deserunt perferendis quisquam minus incidunt nulla sunt facilis culpa labore? Aut at cupiditate laboriosam placeat nostrum ipsam veritatis, delectus iste nobis corrupti exercitationem quidem repudiandae earum fugiat soluta qui asperiores saepe? Dolor, odio labore amet quam sint eius tenetur voluptas iusto animi minus tempore fugiat laudantium alias aliquam distinctio explicabo quaerat mollitia qui. Suscipit sapiente doloribus voluptatem minus esse pariatur voluptate natus beatae, nemo laudantium iste error libero ea magni placeat aliquam? Quod debitis quas eveniet!Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, quis. Pariatur, atque harum culpa provident tempore earum! Cupiditate earum quaerat nihil perferendis? Quas illum, deserunt perferendis quisquam minus incidunt nulla sunt facilis culpa labore? Aut at cupiditate laboriosam placeat nostrum ipsam veritatis, delectus iste nobis corrupti exercitationem quidem repudiandae earum fugiat soluta qui asperiores saepe? Dolor, odio labore amet quam sint eius tenetur voluptas iusto animi minus tempore fugiat laudantium alias aliquam distinctio explicabo quaerat mollitia qui. Suscipit sapiente doloribus voluptatem minus esse pariatur voluptate natus beatae, nemo laudantium iste error libero ea magni placeat aliquam? Quod debitis quas eveniet!Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, quis. Pariatur, atque harum culpa provident tempore earum! Cupiditate earum quaerat nihil perferendis? Quas illum, deserunt perferendis quisquam minus incidunt nulla sunt facilis culpa labore? Aut at cupiditate laboriosam placeat nostrum ipsam veritatis, delectus iste nobis corrupti exercitationem quidem repudiandae earum fugiat soluta qui asperiores saepe? Dolor, odio labore amet quam sint eius tenetur voluptas iusto animi minus tempore fugiat laudantium alias aliquam distinctio explicabo quaerat mollitia qui. Suscipit sapiente doloribus voluptatem minus esse pariatur voluptate natus beatae, nemo laudantium iste error libero ea magni placeat aliquam? Quod debitis quas eveniet!',
         date :'21-08-2022'
	},
	{
		title:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab sit culpa labore officia nam ipsum accusamus quod. Delectus mollitia ipsum explicabo praesentium maxime consequatur corporis non magni eaque debitis repudiandae, necessitatibus nihil quae animi laudantium expedita ab itaque eius placeat voluptatem ducimus voluptas excepturi inventore. Nobis adipisci sequi odit maxime cum est ipsam. Suscipit minima vitae nulla tenetur dolor quam ratione fugit. Modi rerum officia cumque ratione facilis possimus asperiores quaerat adipisci explicabo qui sed architecto, exercitationem saepe autem ipsam!',

		detail:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, quis. Pariatur, atque harum culpa provident tempore earum! Cupiditate earum quaerat nihil perferendis? Quas illum, deserunt perferendis quisquam minus incidunt nulla sunt facilis culpa labore? Aut at cupiditate laboriosam placeat nostrum ipsam veritatis, delectus iste nobis corrupti exercitationem quidem repudiandae earum fugiat soluta qui asperiores saepe? Dolor, odio labore amet quam sint eius tenetur voluptas iusto animi minus tempore fugiat laudantium alias aliquam distinctio explicabo quaerat mollitia qui. Suscipit sapiente doloribus voluptatem minus esse pariatur voluptate natus beatae, nemo laudantium iste error libero ea magni placeat aliquam? Quod debitis quas eveniet!Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, quis. Pariatur, atque harum culpa provident tempore earum! Cupiditate earum quaerat nihil perferendis? Quas illum, deserunt perferendis quisquam minus incidunt nulla sunt facilis culpa labore? Aut at cupiditate laboriosam placeat nostrum ipsam veritatis, delectus iste nobis corrupti exercitationem quidem repudiandae earum fugiat soluta qui asperiores saepe? Dolor, odio labore amet quam sint eius tenetur voluptas iusto animi minus tempore fugiat laudantium alias aliquam distinctio explicabo quaerat mollitia qui. Suscipit sapiente doloribus voluptatem minus esse pariatur voluptate natus beatae, nemo laudantium iste error libero ea magni placeat aliquam? Quod debitis quas eveniet!Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, quis. Pariatur, atque harum culpa provident tempore earum! Cupiditate earum quaerat nihil perferendis? Quas illum, deserunt perferendis quisquam minus incidunt nulla sunt facilis culpa labore? Aut at cupiditate laboriosam placeat nostrum ipsam veritatis, delectus iste nobis corrupti exercitationem quidem repudiandae earum fugiat soluta qui asperiores saepe? Dolor, odio labore amet quam sint eius tenetur voluptas iusto animi minus tempore fugiat laudantium alias aliquam distinctio explicabo quaerat mollitia qui. Suscipit sapiente doloribus voluptatem minus esse pariatur voluptate natus beatae, nemo laudantium iste error libero ea magni placeat aliquam? Quod debitis quas eveniet!',
         date :'21-08-2022'
	},
	{
		title:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab sit culpa labore officia nam ipsum accusamus quod. Delectus mollitia ipsum explicabo praesentium maxime consequatur corporis non magni eaque debitis repudiandae, necessitatibus nihil quae animi laudantium expedita ab itaque eius placeat voluptatem ducimus voluptas excepturi inventore. Nobis adipisci sequi odit maxime cum est ipsam. Suscipit minima vitae nulla tenetur dolor quam ratione fugit. Modi rerum officia cumque ratione facilis possimus asperiores quaerat adipisci explicabo qui sed architecto, exercitationem saepe autem ipsam!',

		detail:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, quis. Pariatur, atque harum culpa provident tempore earum! Cupiditate earum quaerat nihil perferendis? Quas illum, deserunt perferendis quisquam minus incidunt nulla sunt facilis culpa labore? Aut at cupiditate laboriosam placeat nostrum ipsam veritatis, delectus iste nobis corrupti exercitationem quidem repudiandae earum fugiat soluta qui asperiores saepe? Dolor, odio labore amet quam sint eius tenetur voluptas iusto animi minus tempore fugiat laudantium alias aliquam distinctio explicabo quaerat mollitia qui. Suscipit sapiente doloribus voluptatem minus esse pariatur voluptate natus beatae, nemo laudantium iste error libero ea magni placeat aliquam? Quod debitis quas eveniet!Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, quis. Pariatur, atque harum culpa provident tempore earum! Cupiditate earum quaerat nihil perferendis? Quas illum, deserunt perferendis quisquam minus incidunt nulla sunt facilis culpa labore? Aut at cupiditate laboriosam placeat nostrum ipsam veritatis, delectus iste nobis corrupti exercitationem quidem repudiandae earum fugiat soluta qui asperiores saepe? Dolor, odio labore amet quam sint eius tenetur voluptas iusto animi minus tempore fugiat laudantium alias aliquam distinctio explicabo quaerat mollitia qui. Suscipit sapiente doloribus voluptatem minus esse pariatur voluptate natus beatae, nemo laudantium iste error libero ea magni placeat aliquam? Quod debitis quas eveniet!Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, quis. Pariatur, atque harum culpa provident tempore earum! Cupiditate earum quaerat nihil perferendis? Quas illum, deserunt perferendis quisquam minus incidunt nulla sunt facilis culpa labore? Aut at cupiditate laboriosam placeat nostrum ipsam veritatis, delectus iste nobis corrupti exercitationem quidem repudiandae earum fugiat soluta qui asperiores saepe? Dolor, odio labore amet quam sint eius tenetur voluptas iusto animi minus tempore fugiat laudantium alias aliquam distinctio explicabo quaerat mollitia qui. Suscipit sapiente doloribus voluptatem minus esse pariatur voluptate natus beatae, nemo laudantium iste error libero ea magni placeat aliquam? Quod debitis quas eveniet!',
         date :'21-08-2022'
	},
	{
		title:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab sit culpa labore officia nam ipsum accusamus quod. Delectus mollitia ipsum explicabo praesentium maxime consequatur corporis non magni eaque debitis repudiandae, necessitatibus nihil quae animi laudantium expedita ab itaque eius placeat voluptatem ducimus voluptas excepturi inventore. Nobis adipisci sequi odit maxime cum est ipsam. Suscipit minima vitae nulla tenetur dolor quam ratione fugit. Modi rerum officia cumque ratione facilis possimus asperiores quaerat adipisci explicabo qui sed architecto, exercitationem saepe autem ipsam!',

		detail:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, quis. Pariatur, atque harum culpa provident tempore earum! Cupiditate earum quaerat nihil perferendis? Quas illum, deserunt perferendis quisquam minus incidunt nulla sunt facilis culpa labore? Aut at cupiditate laboriosam placeat nostrum ipsam veritatis, delectus iste nobis corrupti exercitationem quidem repudiandae earum fugiat soluta qui asperiores saepe? Dolor, odio labore amet quam sint eius tenetur voluptas iusto animi minus tempore fugiat laudantium alias aliquam distinctio explicabo quaerat mollitia qui. Suscipit sapiente doloribus voluptatem minus esse pariatur voluptate natus beatae, nemo laudantium iste error libero ea magni placeat aliquam? Quod debitis quas eveniet!Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, quis. Pariatur, atque harum culpa provident tempore earum! Cupiditate earum quaerat nihil perferendis? Quas illum, deserunt perferendis quisquam minus incidunt nulla sunt facilis culpa labore? Aut at cupiditate laboriosam placeat nostrum ipsam veritatis, delectus iste nobis corrupti exercitationem quidem repudiandae earum fugiat soluta qui asperiores saepe? Dolor, odio labore amet quam sint eius tenetur voluptas iusto animi minus tempore fugiat laudantium alias aliquam distinctio explicabo quaerat mollitia qui. Suscipit sapiente doloribus voluptatem minus esse pariatur voluptate natus beatae, nemo laudantium iste error libero ea magni placeat aliquam? Quod debitis quas eveniet!Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, quis. Pariatur, atque harum culpa provident tempore earum! Cupiditate earum quaerat nihil perferendis? Quas illum, deserunt perferendis quisquam minus incidunt nulla sunt facilis culpa labore? Aut at cupiditate laboriosam placeat nostrum ipsam veritatis, delectus iste nobis corrupti exercitationem quidem repudiandae earum fugiat soluta qui asperiores saepe? Dolor, odio labore amet quam sint eius tenetur voluptas iusto animi minus tempore fugiat laudantium alias aliquam distinctio explicabo quaerat mollitia qui. Suscipit sapiente doloribus voluptatem minus esse pariatur voluptate natus beatae, nemo laudantium iste error libero ea magni placeat aliquam? Quod debitis quas eveniet!',
         date :'21-08-2022'
	},
];